### ISSUE TITLE
Adding sanitize to the debug mode for CPU

### ISSUE THREAD

**Issue by mohsensadr** [IPPL-framework/ippl#237]
Can we add the flag for sanitizer in the CMakeList for the debug mode?
Maybe, something like
`set (CMAKE_CXX_FLAGS_DEBUG  "-O0 -g -fsanitize=address,undefined")`

https://github.com/IPPL-framework/ippl/blob/21f380c370f752af85f6fce9ceb9a5135556261a/CMakeLists.txt#L40C1-L40C38

**Comment by srikrrish** [comment]
@mohsensadr yes I think this is good. But note I have a few things on my plate and also need to do some work to get the toolchain in Juwels to be able to compile the latest master/dev-3.2.0. So if you want this soon you may want to add this by yourself rather than waiting for me. Sam goes for the other issue you opened also where you assigned me.

**Comment by mohsensadr** [comment]
I see. Sure, I can do it myself
